<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_555043b0d9769',
	'title' => 'NoteDeck Fields',
	'fields' => array (
		array (
			'key' => 'field_555043bfe0e2a',
			'label' => 'NoteDeck',
			'name' => 'note_deck',
			'type' => 'flexible_content',
			'instructions' => 'A deck is made of slides. Add as many slides as you\'d like to this deck by pressing "Add New Slide."',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add New Slide',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '555043c95fc49',
					'name' => 'video_section',
					'label' => 'Video Slide',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_555043f1e0e2e',
							'label' => 'Video URL',
							'name' => 'video_url',
							'type' => 'text',
							'instructions' => 'Only use Vimeo or YouTube',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 70,
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_55504405e0e2f',
							'label' => 'Video Type',
							'name' => 'video_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => 30,
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'youtube' => 'YouTube',
								'vimeo' => 'Vimeo',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'vertical',
						),
						array (
							'key' => 'field_5563ea48ae25e',
							'label' => 'Background Color',
							'name' => 'video_background',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#efefef',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '555043d6e0e2b',
					'name' => 'image_section',
					'label' => 'Image Slide',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_55504430e0e30',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_55504442e0e31',
							'label' => 'External Link',
							'name' => 'image_link',
							'type' => 'text',
							'instructions' => 'If you enter a value here, the slide will become clickable and open links in a new browser window.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'http://',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_5563e8969e7ff',
							'label' => 'Background Color',
							'name' => 'image_background',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#efefef',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '555043dee0e2c',
					'name' => 'text_section',
					'label' => 'Text Slide',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_555044d4e825c',
							'label' => 'Content',
							'name' => 'text_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_556b774d7af77',
							'label' => 'Content Color',
							'name' => 'text_content_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
						array (
							'key' => 'field_555046934b1b1',
							'label' => 'Background Type',
							'name' => 'background_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'Default' => 'Default',
								'Solid Color' => 'Solid Color',
								'Background Image' => 'Background Image',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
						),
						array (
							'key' => 'field_555046f64b1b3',
							'label' => 'Background Color',
							'name' => 'background_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_555046934b1b1',
										'operator' => '==',
										'value' => 'Solid Color',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
						array (
							'key' => 'field_555046dc4b1b2',
							'label' => 'Background Image',
							'name' => 'background_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_555046934b1b1',
										'operator' => '==',
										'value' => 'Background Image',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_556b79f7697ea',
							'label' => 'Notes Button',
							'name' => 'notes_button',
							'type' => 'true_false',
							'instructions' => 'This will determine whether or not the user has the option to add additional notes and email themselves the section.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '555043e7e0e2d',
					'name' => 'slider_section',
					'label' => 'Slider Slide',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_555044ece825d',
							'label' => 'Images',
							'name' => 'slider_item',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'layout' => 'table',
							'button_label' => 'Add Slider Image',
							'sub_fields' => array (
								array (
									'key' => 'field_55504559e825e',
									'label' => 'Image',
									'name' => 'slider_image',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'url',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'key' => 'field_55504568e825f',
									'label' => 'Link',
									'name' => 'slider_url',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
							),
						),
						array (
							'key' => 'field_556aab88948c4',
							'label' => 'Slider Speed',
							'name' => 'slider_speed',
							'type' => 'number',
							'instructions' => 'Enter the time you want between slide transitions in milliseconds.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_556aab68948c3',
							'label' => 'Slider Background',
							'name' => 'slider_background',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'deck_decks',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'slug',
		5 => 'format',
		6 => 'categories',
		7 => 'tags',
		8 => 'send-trackbacks',
	),
));

acf_add_local_field_group(array (
	'key' => 'group_556bec382c46e',
	'title' => 'NoteDeck Email Settings',
	'fields' => array (
		array (
			'key' => 'field_5591a3507e60d',
			'label' => 'License Key',
			'name' => 'license_key',
			'type' => 'text',
			'instructions' => 'Please enter your license key to register your version of the plugin and enable updates.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => '',
						'operator' => '==',
						'value' => '',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_556bf0d1cf40c',
			'label' => 'Sent From: Name',
			'name' => 'notes_email_name',
			'type' => 'text',
			'instructions' => 'This is the name that emails sent through NoteDeck will say they are from.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_556bec44a37a8',
			'label' => 'Sent From: Email',
			'name' => 'notes_email_from',
			'type' => 'email',
			'instructions' => 'This is the email address that emails sent out by NoteDeck will say they are from.

Will use admin email if left blank.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_556bed09a37a9',
			'label' => 'Subject Field',
			'name' => 'notes_email_subject',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_556e34521dff5',
			'label' => 'Email Footer',
			'name' => 'notes_email_footer',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '~~~~~~~~~~~~~~~
Sent via NoteDeck',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'notedeck-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_558c8a39e876e',
	'title' => 'Theme',
	'fields' => array (
		array (
			'key' => 'field_558c8a410180f',
			'label' => 'Use WordPress Theme?',
			'name' => 'in_theme',
			'type' => 'true_false',
			'instructions' => 'If checked your deck will show up wrapped inside of your current WordPress Theme. Otherwise it will show up in its own default blank page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'deck_decks',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;